version: "3.8"
services:
  mongo:
    image: mongo:6.0.7-jammy
    restart: always
    networks:
      - mongonet
    environment:
      MONGO_INITDB_ROOT_USERNAME: easylearnz
      MONGO_INITDB_ROOT_PASSWORD: easylearnz
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
networks:
  mongonet:
